# ChainBot ALEX OS Module Configuration
# Default configuration file

module:
  name: chainbot
  version: "1.0.0"
  description: "Advanced workflow orchestration engine with AI agent management"
  log_level: INFO
  debug: false

database:
  url: postgresql://chainbot:password@localhost:5432/chainbot
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600
  echo: false

api:
  host: 127.0.0.1
  port: 9000
  debug: false
  workers: 1
  timeout: 30
  cors_origins: ["http://localhost:3000", "http://127.0.0.1:3000"]

# GPT Integration Configuration
gpt_integration:
  enabled: true
  default_provider: "openai"  # openai or maclink
  
  openai:
    enabled: true
    api_key: ""  # Set via environment variable OPENAI_API_KEY
    organization_id: ""  # Optional
    default_model: "gpt-4o"
    max_tokens: 2048
    temperature: 0.7
    timeout: 30
    max_retries: 3
    rate_limit_requests_per_minute: 60
    rate_limit_tokens_per_minute: 150000
    
  maclink:
    enabled: true
    macbook_url: "http://localhost:8080"  # MacBook MacLink server URL
    api_key: ""  # Optional
    default_model: "llama2"
    max_tokens: 2048
    temperature: 0.7
    timeout: 60
    max_retries: 3
    health_check_interval: 30
    
  agent_brain:
    enabled: true
    conversation_history_limit: 50
    context_window_size: 10
    confidence_threshold: 0.7
    fallback_provider: "openai"
    persona_cache_size: 100

security:
  secret_key: "your-secret-key-here-change-in-production"
  algorithm: HS256
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
  password_min_length: 8
  bcrypt_rounds: 12

logging:
  level: INFO
  file: /var/log/alex_os/chainbot.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_size: 10485760  # 10MB
  backup_count: 5
  console: true

alex_os:
  event_bus_url: ws://10.42.69.208:8000/ws/events
  webhook_url: http://127.0.0.1:8000/api/webhooks/chainbot
  health_check_interval: 30
  metrics_enabled: true
  module_registry_url: http://10.42.69.208:8000/api/modules
  integration_timeout: 60

workflow_engine:
  max_concurrent_workflows: 10
  max_workflow_duration: 3600  # 1 hour
  retry_attempts: 3
  retry_delay: 5
  workflow_timeout: 1800  # 30 minutes
  cleanup_interval: 300  # 5 minutes
  max_workflow_history: 1000

agent_management:
  max_agents: 50
  agent_timeout: 300  # 5 minutes
  spawn_interval: 5
  max_agent_memory: 512  # MB
  agent_heartbeat_interval: 30
  agent_cleanup_interval: 600  # 10 minutes
  agent_types:
    assistant:
      max_instances: 20
      memory_limit: 256
    data_processor:
      max_instances: 15
      memory_limit: 512
    api:
      max_instances: 10
      memory_limit: 128
    workflow:
      max_instances: 5
      memory_limit: 256

entanglement:
  max_entanglements: 25
  entanglement_timeout: 1800  # 30 minutes
  coordination_interval: 10
  max_agents_per_entanglement: 10
  cleanup_interval: 600  # 10 minutes

websocket:
  max_connections: 100
  ping_interval: 30
  ping_timeout: 10
  close_timeout: 10
  max_message_size: 1048576  # 1MB

audit:
  enabled: true
  log_level: INFO
  retention_days: 90
  max_log_size: 104857600  # 100MB
  compression: true
  sensitive_fields: ["password", "token", "secret"]

monitoring:
  metrics_enabled: true
  prometheus_enabled: true
  health_check_interval: 30
  performance_monitoring: true
  alerting:
    enabled: true
    cpu_threshold: 80
    memory_threshold: 80
    disk_threshold: 90
    error_rate_threshold: 5

raspberry_pi:
  hardware_monitoring: true
  temperature_threshold: 70  # Celsius
  cpu_frequency_monitoring: true
  memory_monitoring: true
  disk_monitoring: true
  network_monitoring: true
  gpio_monitoring: false

performance:
  cache_enabled: true
  cache_ttl: 300  # 5 minutes
  cache_max_size: 1000
  connection_pooling: true
  async_processing: true
  background_tasks: true

development:
  auto_reload: false
  debug_mode: false
  test_mode: false
  mock_services: false
  sample_data: false 